from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from utils.searxng_settings import (
    build_settings_from_env,
    load_env_files,
    main,
    parse_proxy_urls,
)


class SearxngSettingsTests(unittest.TestCase):
    def test_parse_proxy_urls_accepts_comma_newline_and_dedupes(self):
        proxies = parse_proxy_urls(
            "http://proxy1:8080, socks5h://proxy2:1080\n"
            "http://proxy1:8080"
        )

        self.assertEqual(proxies, ("http://proxy1:8080", "socks5h://proxy2:1080"))

    def test_parse_proxy_urls_rejects_invalid_proxy(self):
        with self.assertRaises(ValueError):
            parse_proxy_urls("ftp://proxy.example.test:21")

    def test_build_settings_without_proxy_omits_outgoing_block(self):
        text = build_settings_from_env({"SEARXNG_OUTGOING_PROXIES": ""})

        self.assertIn("keep_only:", text)
        self.assertNotIn("outgoing:", text)

    def test_build_settings_with_proxy_adds_outgoing_proxy_block(self):
        text = build_settings_from_env({
            "SEARXNG_OUTGOING_PROXIES": "http://proxy1:8080,socks5h://proxy2:1080",
            "SEARXNG_EXTRA_PROXY_TIMEOUT": "10",
        })

        self.assertIn("outgoing:", text)
        self.assertIn("  proxies:", text)
        self.assertIn("    all://:", text)
        self.assertIn('      - "http://proxy1:8080"', text)
        self.assertIn('      - "socks5h://proxy2:1080"', text)
        self.assertIn("  extra_proxy_timeout: 10.0", text)

    def test_load_env_files_uses_later_files_as_override(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.env"
            second = Path(tmp) / "second.env"
            first.write_text("SEARXNG_OUTGOING_PROXIES=http://proxy1:8080\n", encoding="utf-8")
            second.write_text("SEARXNG_OUTGOING_PROXIES=http://proxy2:8080\n", encoding="utf-8")

            values = load_env_files([first, second], include_process_env=False)

        self.assertEqual(values["SEARXNG_OUTGOING_PROXIES"], "http://proxy2:8080")

    def test_main_writes_generated_settings_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            env_file = Path(tmp) / ".env"
            output = Path(tmp) / "settings.yml"
            env_file.write_text("SEARXNG_OUTGOING_PROXIES=http://proxy1:8080\n", encoding="utf-8")

            exit_code = main(["--env-file", str(env_file), "--output", str(output)])

            text = output.read_text(encoding="utf-8")

        self.assertEqual(exit_code, 0)
        self.assertIn("Generated by utils.searxng_settings", text)
        self.assertIn('      - "http://proxy1:8080"', text)


if __name__ == "__main__":
    unittest.main()
