from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from urllib.parse import urlparse

SEARXNG_OUTGOING_PROXIES_ENV = "SEARXNG_OUTGOING_PROXIES"
SEARXNG_EXTRA_PROXY_TIMEOUT_ENV = "SEARXNG_EXTRA_PROXY_TIMEOUT"
ALLOWED_PROXY_SCHEMES = {"http", "https", "socks4", "socks4a", "socks5", "socks5h"}
LOCAL_SETTINGS_HEADER = "# Generated by utils.searxng_settings. Edit .env, not this file."
BASE_LOCAL_SETTINGS = """use_default_settings:
  engines:
    keep_only:
      - bing
      - google

search:
  safe_search: 0
  default_lang: "zh-TW"
  formats:
    - html
    - json

server:
  secret_key: "configured-by-env"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"
"""


def parse_proxy_urls(value: str) -> tuple[str, ...]:
    proxies: list[str] = []
    for item in re.split(r"[\s,]+", str(value or "").strip()):
        proxy_url = item.strip()
        if not proxy_url:
            continue
        _validate_proxy_url(proxy_url)
        if proxy_url not in proxies:
            proxies.append(proxy_url)
    return tuple(proxies)


def build_settings_from_env(env: dict[str, str]) -> str:
    proxies = parse_proxy_urls(env.get(SEARXNG_OUTGOING_PROXIES_ENV, ""))
    extra_timeout = _parse_extra_proxy_timeout(env.get(SEARXNG_EXTRA_PROXY_TIMEOUT_ENV, ""))
    return build_settings(proxies, extra_proxy_timeout=extra_timeout)


def build_settings(proxies: tuple[str, ...], *, extra_proxy_timeout: float | None = None) -> str:
    parts = [LOCAL_SETTINGS_HEADER, BASE_LOCAL_SETTINGS.rstrip()]
    if proxies:
        parts.append(_build_outgoing_block(proxies, extra_proxy_timeout=extra_proxy_timeout))
    return "\n\n".join(parts).rstrip() + "\n"


def load_env_files(paths: list[Path], *, include_process_env: bool = True) -> dict[str, str]:
    values: dict[str, str] = {}
    for path in paths:
        if path and path.is_file():
            values.update(_read_env_file(path))
    if include_process_env:
        values.update(os.environ)
    return values


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate local SearXNG settings.yml")
    parser.add_argument("--env-file", action="append", default=[], help="dotenv file to read; later files override earlier files")
    parser.add_argument("--output", required=True, help="settings.yml output path")
    args = parser.parse_args(argv)
    env_files = [Path(path) for path in args.env_file]
    settings = build_settings_from_env(load_env_files(env_files))
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(settings, encoding="utf-8")
    return 0


def _validate_proxy_url(proxy_url: str) -> None:
    parsed = urlparse(proxy_url)
    if parsed.scheme.lower() not in ALLOWED_PROXY_SCHEMES or not parsed.netloc:
        raise ValueError("invalid SearXNG outgoing proxy URL")


def _parse_extra_proxy_timeout(value: str) -> float | None:
    normalized = str(value or "").strip()
    if not normalized:
        return None
    try:
        timeout = float(normalized)
    except ValueError as exc:
        raise ValueError("invalid SearXNG extra proxy timeout") from exc
    if timeout <= 0:
        raise ValueError("invalid SearXNG extra proxy timeout")
    return timeout


def _build_outgoing_block(proxies: tuple[str, ...], *, extra_proxy_timeout: float | None) -> str:
    lines = ["outgoing:", "  proxies:", "    all://:"]
    lines.extend(f"      - {json.dumps(proxy)}" for proxy in proxies)
    if extra_proxy_timeout is not None:
        lines.append(f"  extra_proxy_timeout: {extra_proxy_timeout:.1f}")
    return "\n".join(lines)


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        key, value = _parse_env_line(line)
        if key:
            values[key] = value
    return values


def _parse_env_line(line: str) -> tuple[str, str]:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or "=" not in stripped:
        return "", ""
    key, value = stripped.split("=", 1)
    key = key.strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
        return "", ""
    return key, _strip_env_value(value)


def _strip_env_value(value: str) -> str:
    stripped = value.strip()
    if len(stripped) >= 2 and stripped[0] == stripped[-1] and stripped[0] in {"'", '"'}:
        return stripped[1:-1]
    return stripped


if __name__ == "__main__":
    raise SystemExit(main())
